### ISSUE TITLE
emr patch ergonomics improvements

### ISSUE THREAD

**Issue by vpipkt** [s22s/raster-frames#49]
Two small things

Make the `update-emr-zeppelin` script not require a keypair argument. if it is missing pass nothing on to the `aws emr` commands and they fall back to configured emr keypair in user's environment

When putting the assembly jar on the EMR master node copy to a consistent file name (without version) so that our preamble %dep blocks can be consistent, eg

```
%dep
z.load("aee-assembly.jar")
```

(name won't change when we update snapshot versions etc)

**Comment by metasim** [comment]
This belongs in our private repo.
