### ISSUE TITLE
allow setting of numPartitions in geotrellis datasource query

### ISSUE THREAD

**Issue by mteldridge** [s22s/raster-frames#53]
It would be useful to allow users to specify a numPartitions parameter in the query for geotrellis layers.  
`FilteringLayerQuery.query()`can take this parameter. 

 https://github.com/s22s/raster-frames/blob/47dae36c996dc166488b4d83146bcaec4ea33cd3/datasource/src/main/scala/astraea/spark/rasterframes/datasource/geotrellis/GeoTrellisRelation.scala#L245

**Comment by vpipkt** [comment]
looks like there is precedent for DataFrameReader option named `numPartitions`

https://spark.apache.org/docs/latest/sql-programming-guide.html#jdbc-to-other-databases
