### ISSUE TITLE
Correct data cells count for int types in`tileStats(t)("dataCells")` 

### ISSUE THREAD

**Issue by vpipkt** [s22s/raster-frames#57]
The  `dataCells` field of `tileStats` is not consistent with the expected number of data cells when dealing with Integer `CellType`s. This may be limited to integer types without a nodata specified, e.g. `BitCellType`, `ByteCellType`, ... `IntCellType`.

Root cause may be   calls to `tileStats` always call `statisticsDouble` on any tile type passed in.

**Comment by vpipkt** [comment]
see branch `feature/fix-tileStats-dataCells-for-int`

**Comment by metasim** [comment]
It's likely the approximate nature of `statisticsDouble`. I've been meaning to rethink some of that code anyway.

**Comment by vpipkt** [comment]
Not sure if it matters whether the tile type has NoData or not... there are still some edge cases to look at

**Comment by vpipkt** [comment]
PR to fix is merged. Closing...
